    - name: Python | install python-pip
      package: name=python-pip state=latest
      become: yes
      tags:
        -setup
        -python

    - name: Python | Update pip
      shell: pip install -U pip
      become: yes
      tags:
        -setup
        -python

    - name: Python | install python-dev
      package: name=python-dev update_cache=yes state=latest
      when: ansible_os_family == "Debian"
      become: yes
      tags:
        -setup
        -python
