  - name: Docker | Check if is present
    command: test -x /usr/bin/docker
    ignore_errors: yes
    register: docker_present
    tags:
        -docker

  - name: Python | install wget
    package: name=wget state=present
    become: yes
    tags:
      -docker

  - name: Docker | Add docker gpg keys
    shell: wget -qO- https://get.docker.com/gpg | apt-key add -
    when: docker_present|failed and ansible_os_family == "Debian"
    become: yes
    tags:
        -docker

  - name: Docker | Install docker via web installer
    shell: wget -qO- https://get.docker.com/ | sh
    when:  docker_present|failed
    become: yes
    tags:
        -docker

  - name: Docker | Add current user to docker group
    user: name={{ deploy_user }} groups=docker append=yes
    become: yes
    tags:
        -docker
