---

  - name: Docker | Ensure service started
    service: name=docker state=started
    become: yes


  - name: Docker | Load and start registry image (v2)
    shell: docker inspect registry | grep Status
    register: registry_status
    ignore_errors: true


  - name: Docker | Load and start registry image (v2)
    shell: docker run -d -p 5000:5000 --restart=always --name registry registry:2
    when: registry_status | failed
