---
- name: DOCKER REGISTRY | Ensure Docker service started
  ansible.builtin.service:
    name: docker
    state: started
  become: true

- name: DOCKER REGISTRY | Check registry container status
  ansible.builtin.shell:
    cmd: docker inspect registry | grep Status
  register: registry_status
  ignore_errors: true
  changed_when: false

- name: DOCKER REGISTRY | Start registry container
  ansible.builtin.shell:
    cmd: docker run -d -p 5000:5000 --restart=always --name registry registry:2
  when: registry_status is failed
  tags:
    - skip_ansible_lint
