---
- name: Converge
  hosts: all

  pre_tasks:
    - debug: msg="Pre tasks section for {{ansible_host}}"

    - set_fact:
        remote_ip_address: "{{ ansible_host }}"

    - include_vars: "playbook_vars.yml"

  roles:
     - {
        role: "sa-docker",
        option_install_docker_compose: true,
        option_install_docker_registry: false,
        option_install_docker_python: false
       }
