---
- name: Converge
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: auto

  pre_tasks:
    - debug: var="role_under_test"
  vars:
    ansible_python_interpreter: auto
#  roles:
#    - {
#        role: "{{ role_under_test | default('role_under_test') }}",
#        firewall_used: docker,
#        docker_test: true,
#        preferred_python_version: "3"
#      }
  tasks:
   - name: Apply role runtime
     include_role:
       name: "{{ role_under_test | default('role_under_test') }}"
     vars:
       firewall_used: docker,
       docker_test: true,
       preferred_python_version: "3"
